ALTER TABLE "Student" ADD COLUMN "portraitOffsetX" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Student" ADD COLUMN "portraitOffsetY" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Student" ADD COLUMN "portraitScale" DOUBLE PRECISION NOT NULL DEFAULT 1;
