ALTER TABLE "Student" ADD COLUMN "memorialOffsetX" DOUBLE PRECISION NOT NULL DEFAULT -7.6;
ALTER TABLE "Student" ADD COLUMN "memorialOffsetY" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Student" ADD COLUMN "memorialScale" DOUBLE PRECISION NOT NULL DEFAULT 0.5;
